python making_sense.py add gpt r
python making_sense.py del gpt r
python making_sense.py sub gpt r
python making_sense.py swap gpt r
python making_sense.py add gpt-2 r
python making_sense.py del gpt-2 r
python making_sense.py sub gpt-2 r
python making_sense.py swap gpt-2 r
python making_sense.py add bert r
python making_sense.py del bert r
python making_sense.py sub bert r
python making_sense.py swap bert r
python making_sense.py add roberta r
python making_sense.py del roberta r
python making_sense.py sub roberta r
python making_sense.py swap roberta r
python making_sense.py add xlnet r
python making_sense.py del xlnet r
python making_sense.py sub xlnet r
python making_sense.py swap xlnet r
